# Generated by Django 5.0.3 on 2024-04-21 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='person',
            name='people',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_subtext',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_subtext',
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_text', models.CharField(max_length=200)),
                ('event_subtext', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.event')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_text', models.CharField(max_length=200)),
                ('person_subtext', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
