# Generated by Django 5.0.3 on 2024-05-03 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_remove_eventdetail_event_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.person')),
            ],
        ),
    ]
