# Generated by Django 5.0.4 on 2024-05-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
