# Generated by Django 5.0.6 on 2024-05-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_food_alter_eventimage_image_fooddetail_foodimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothe_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClotheDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothe_subtext', models.TextField()),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.clothe')),
            ],
        ),
        migrations.CreateModel(
            name='ClotheImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothes/')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=100)),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.clothe')),
            ],
        ),
    ]
