# Generated by Django 5.0.6 on 2024-05-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_clothe_clothedetail_clotheimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livelihood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livelihood_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LivelihoodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livelihood_subtext', models.TextField()),
                ('livelihood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.livelihood')),
            ],
        ),
        migrations.CreateModel(
            name='LivelihoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='livelihoods/')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=100)),
                ('livelihood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.livelihood')),
            ],
        ),
    ]
