# Generated by Django 5.0.6 on 2024-05-10 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0010_culture_culturedetail_cultureimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_subtext', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medicines/')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.medicine')),
            ],
        ),
    ]
