# Generated by Django 5.0.6 on 2024-05-10 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0011_medicine_medicinedetail_medicineimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InventionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_subtext', models.TextField()),
                ('invention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.invention')),
            ],
        ),
        migrations.CreateModel(
            name='InventionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inventions/')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=100)),
                ('invention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.invention')),
            ],
        ),
    ]
